# Setup
title:        "Jalil's Portfolio"
tagline:      "Description of my github projects"
baseurl:      ""
locale:       "en"


# About/contact
author:
  name:       "Abdeljalil Moussa"
  url:        "jalil.msa@gmail.com"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
